// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'d091be57a839d058217118f45136f0ad18e27b63b613367bcdeb7d66e6ba6757'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Categories: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly categoryName: Varchar<255>;
      readonly description: Varchar<255>;
    };
    readonly OrderItens: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly idOrder: CodecTypes['pg/int4@1']['output'];
      readonly idVariant: CodecTypes['pg/int4@1']['output'];
      readonly quantity: CodecTypes['pg/int4@1']['output'];
      readonly unitPrice: CodecTypes['pg/int4@1']['output'];
    };
    readonly Orders: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly idUser: CodecTypes['pg/int4@1']['output'];
      readonly orderDate: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly orderStatus: 'concluído' | 'em processo' | 'recusado';
    };
    readonly Payment: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly idUser: CodecTypes['pg/int4@1']['output'];
      readonly idOrder: CodecTypes['pg/int4@1']['output'];
      readonly paymentDate: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly paymentMetod: 'pix' | 'cartão' | 'boleto' | 'paypal';
      readonly paymentStatus: 'concluído' | 'em processo' | 'recusado';
      readonly id_transacao_gateway: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly Product: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: Varchar<255>;
      readonly idCategory: CodecTypes['pg/int4@1']['output'];
      readonly price: CodecTypes['pg/int4@1']['output'];
      readonly stock: CodecTypes['pg/int4@1']['output'];
      readonly description: Varchar<255>;
    };
    readonly User: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly email: Varchar<150>;
      readonly name: Varchar<100>;
      readonly adress: Varchar<255>;
      readonly password: CodecTypes['pg/text@1']['output'];
      readonly userName: CodecTypes['pg/text@1']['output'];
    };
    readonly Variants: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: Varchar<255>;
      readonly idProduct: CodecTypes['pg/int4@1']['output'];
      readonly color: Varchar<255>;
      readonly stock: CodecTypes['pg/int4@1']['output'];
      readonly variantCode: CodecTypes['pg/int4@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Categories: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly categoryName: CodecTypes['sql/varchar@1']['input'];
      readonly description: CodecTypes['sql/varchar@1']['input'];
    };
    readonly OrderItens: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly idOrder: CodecTypes['pg/int4@1']['input'];
      readonly idVariant: CodecTypes['pg/int4@1']['input'];
      readonly quantity: CodecTypes['pg/int4@1']['input'];
      readonly unitPrice: CodecTypes['pg/int4@1']['input'];
    };
    readonly Orders: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly idUser: CodecTypes['pg/int4@1']['input'];
      readonly orderDate: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly orderStatus: 'concluído' | 'em processo' | 'recusado';
    };
    readonly Payment: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly idUser: CodecTypes['pg/int4@1']['input'];
      readonly idOrder: CodecTypes['pg/int4@1']['input'];
      readonly paymentDate: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly paymentMetod: 'pix' | 'cartão' | 'boleto' | 'paypal';
      readonly paymentStatus: 'concluído' | 'em processo' | 'recusado';
      readonly id_transacao_gateway: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly Product: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['sql/varchar@1']['input'];
      readonly idCategory: CodecTypes['pg/int4@1']['input'];
      readonly price: CodecTypes['pg/int4@1']['input'];
      readonly stock: CodecTypes['pg/int4@1']['input'];
      readonly description: CodecTypes['sql/varchar@1']['input'];
    };
    readonly User: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly email: CodecTypes['sql/varchar@1']['input'];
      readonly name: CodecTypes['sql/varchar@1']['input'];
      readonly adress: CodecTypes['sql/varchar@1']['input'];
      readonly password: CodecTypes['pg/text@1']['input'];
      readonly userName: CodecTypes['pg/text@1']['input'];
    };
    readonly Variants: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['sql/varchar@1']['input'];
      readonly idProduct: CodecTypes['pg/int4@1']['input'];
      readonly color: CodecTypes['sql/varchar@1']['input'];
      readonly stock: CodecTypes['pg/int4@1']['input'];
      readonly variantCode: CodecTypes['pg/int4@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly categories: {
      readonly categoryName: Varchar<255>;
      readonly description: Varchar<255>;
      readonly id: CodecTypes['pg/int4@1']['output'];
    };
    readonly orderItens: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly idOrder: CodecTypes['pg/int4@1']['output'];
      readonly idVariant: CodecTypes['pg/int4@1']['output'];
      readonly quantity: CodecTypes['pg/int4@1']['output'];
      readonly unitPrice: CodecTypes['pg/int4@1']['output'];
    };
    readonly orders: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly idUser: CodecTypes['pg/int4@1']['output'];
      readonly orderDate: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly orderStatus: 'concluído' | 'em processo' | 'recusado';
    };
    readonly payment: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly id_transacao_gateway: CodecTypes['pg/text@1']['output'] | null;
      readonly idOrder: CodecTypes['pg/int4@1']['output'];
      readonly idUser: CodecTypes['pg/int4@1']['output'];
      readonly paymentDate: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly paymentMetod: 'pix' | 'cartão' | 'boleto' | 'paypal';
      readonly paymentStatus: 'concluído' | 'em processo' | 'recusado';
    };
    readonly product: {
      readonly description: Varchar<255>;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly idCategory: CodecTypes['pg/int4@1']['output'];
      readonly name: Varchar<255>;
      readonly price: CodecTypes['pg/int4@1']['output'];
      readonly stock: CodecTypes['pg/int4@1']['output'];
    };
    readonly user: {
      readonly adress: Varchar<255>;
      readonly email: Varchar<150>;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly name: Varchar<100>;
      readonly password: CodecTypes['pg/text@1']['output'];
      readonly userName: CodecTypes['pg/text@1']['output'];
    };
    readonly variants: {
      readonly color: Varchar<255>;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly idProduct: CodecTypes['pg/int4@1']['output'];
      readonly name: Varchar<255>;
      readonly stock: CodecTypes['pg/int4@1']['output'];
      readonly variantCode: CodecTypes['pg/int4@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly categories: {
      readonly categoryName: CodecTypes['sql/varchar@1']['input'];
      readonly description: CodecTypes['sql/varchar@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
    };
    readonly orderItens: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly idOrder: CodecTypes['pg/int4@1']['input'];
      readonly idVariant: CodecTypes['pg/int4@1']['input'];
      readonly quantity: CodecTypes['pg/int4@1']['input'];
      readonly unitPrice: CodecTypes['pg/int4@1']['input'];
    };
    readonly orders: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly idUser: CodecTypes['pg/int4@1']['input'];
      readonly orderDate: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly orderStatus: 'concluído' | 'em processo' | 'recusado';
    };
    readonly payment: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly id_transacao_gateway: CodecTypes['pg/text@1']['input'] | null;
      readonly idOrder: CodecTypes['pg/int4@1']['input'];
      readonly idUser: CodecTypes['pg/int4@1']['input'];
      readonly paymentDate: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly paymentMetod: 'pix' | 'cartão' | 'boleto' | 'paypal';
      readonly paymentStatus: 'concluído' | 'em processo' | 'recusado';
    };
    readonly product: {
      readonly description: CodecTypes['sql/varchar@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly idCategory: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['sql/varchar@1']['input'];
      readonly price: CodecTypes['pg/int4@1']['input'];
      readonly stock: CodecTypes['pg/int4@1']['input'];
    };
    readonly user: {
      readonly adress: CodecTypes['sql/varchar@1']['input'];
      readonly email: CodecTypes['sql/varchar@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['sql/varchar@1']['input'];
      readonly password: CodecTypes['pg/text@1']['input'];
      readonly userName: CodecTypes['pg/text@1']['input'];
    };
    readonly variants: {
      readonly color: CodecTypes['sql/varchar@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly idProduct: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['sql/varchar@1']['input'];
      readonly stock: CodecTypes['pg/int4@1']['input'];
      readonly variantCode: CodecTypes['pg/int4@1']['input'];
    };
  };
};

export namespace Models {
  export type public_Categories = {
    id: CodecTypes['pg/int4@1']['output'];
    categoryName: Varchar<255>;
    description: Varchar<255>;
    Product: public_Product[];
    readonly [RelationKeys]?: 'Product';
  };
  export type public_OrderItens = {
    id: CodecTypes['pg/int4@1']['output'];
    idOrder: CodecTypes['pg/int4@1']['output'];
    idVariant: CodecTypes['pg/int4@1']['output'];
    quantity: CodecTypes['pg/int4@1']['output'];
    unitPrice: CodecTypes['pg/int4@1']['output'];
    Orders: public_Orders;
    Variants: public_Variants;
    readonly [RelationKeys]?: 'Orders' | 'Variants';
  };
  export type public_Orders = {
    id: CodecTypes['pg/int4@1']['output'];
    idUser: CodecTypes['pg/int4@1']['output'];
    orderDate: CodecTypes['pg/timestamptz-string@1']['output'];
    orderStatus: 'concluído' | 'em processo' | 'recusado';
    OrderItens: public_OrderItens[];
    Payment: public_Payment[];
    User: public_User;
    readonly [RelationKeys]?: 'OrderItens' | 'Payment' | 'User';
  };
  export type public_Payment = {
    id: CodecTypes['pg/int4@1']['output'];
    idUser: CodecTypes['pg/int4@1']['output'];
    idOrder: CodecTypes['pg/int4@1']['output'];
    paymentDate: CodecTypes['pg/timestamptz-string@1']['output'];
    paymentMetod: 'pix' | 'cartão' | 'boleto' | 'paypal';
    paymentStatus: 'concluído' | 'em processo' | 'recusado';
    id_transacao_gateway: CodecTypes['pg/text@1']['output'] | null;
    Orders: public_Orders;
    User: public_User;
    readonly [RelationKeys]?: 'Orders' | 'User';
  };
  export type public_Product = {
    id: CodecTypes['pg/int4@1']['output'];
    name: Varchar<255>;
    idCategory: CodecTypes['pg/int4@1']['output'];
    price: CodecTypes['pg/int4@1']['output'];
    stock: CodecTypes['pg/int4@1']['output'];
    description: Varchar<255>;
    Categories: public_Categories;
    Variants: public_Variants[];
    readonly [RelationKeys]?: 'Categories' | 'Variants';
  };
  export type public_User = {
    id: CodecTypes['pg/int4@1']['output'];
    email: Varchar<150>;
    name: Varchar<100>;
    adress: Varchar<255>;
    password: CodecTypes['pg/text@1']['output'];
    userName: CodecTypes['pg/text@1']['output'];
    Orders: public_Orders[];
    Payment: public_Payment[];
    readonly [RelationKeys]?: 'Orders' | 'Payment';
  };
  export type public_Variants = {
    id: CodecTypes['pg/int4@1']['output'];
    name: Varchar<255>;
    idProduct: CodecTypes['pg/int4@1']['output'];
    color: Varchar<255>;
    stock: CodecTypes['pg/int4@1']['output'];
    variantCode: CodecTypes['pg/int4@1']['output'];
    OrderItens: public_OrderItens[];
    Product: public_Product;
    readonly [RelationKeys]?: 'OrderItens' | 'Product';
  };
}

export declare const models: {
  public: {
    Categories: Models.public_Categories;
    OrderItens: Models.public_OrderItens;
    Orders: Models.public_Orders;
    Payment: Models.public_Payment;
    Product: Models.public_Product;
    User: Models.public_User;
    Variants: Models.public_Variants;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly categories: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly categoryName: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 255 };
                };
                readonly description: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 255 };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly orderItens: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly idOrder: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly idVariant: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly quantity: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly unitPrice: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'orderItens_idOrder_idx_13561201';
                  readonly prefix: 'orderItens_idOrder_idx';
                  readonly columns: readonly ['idOrder'];
                  readonly unique: false;
                },
                {
                  readonly name: 'orderItens_idVariant_idx_ba13bdf6';
                  readonly prefix: 'orderItens_idVariant_idx';
                  readonly columns: readonly ['idVariant'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'orderItens';
                    readonly columns: readonly ['idOrder'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'orders';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'orderItens';
                    readonly columns: readonly ['idVariant'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'variants';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly orders: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly idUser: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly orderDate: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly orderStatus: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'em processo'>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'orders_idUser_idx_6acaa521';
                  readonly prefix: 'orders_idUser_idx';
                  readonly columns: readonly ['idUser'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'orders';
                    readonly columns: readonly ['idUser'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly payment: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly idUser: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly idOrder: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly paymentDate: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly paymentMetod: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly paymentStatus: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly id_transacao_gateway: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'payment_idOrder_idx_13561201';
                  readonly prefix: 'payment_idOrder_idx';
                  readonly columns: readonly ['idOrder'];
                  readonly unique: false;
                },
                {
                  readonly name: 'payment_idUser_idx_6acaa521';
                  readonly prefix: 'payment_idUser_idx';
                  readonly columns: readonly ['idUser'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'payment';
                    readonly columns: readonly ['idOrder'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'orders';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'payment';
                    readonly columns: readonly ['idUser'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'user';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly product: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly name: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 255 };
                };
                readonly idCategory: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly price: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly stock: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly description: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 255 };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'product_idCategory_idx_f7a5d9d3';
                  readonly prefix: 'product_idCategory_idx';
                  readonly columns: readonly ['idCategory'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'product';
                    readonly columns: readonly ['idCategory'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'categories';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly user: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly email: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 150 };
                };
                readonly name: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 100 };
                };
                readonly adress: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 255 };
                };
                readonly password: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly userName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['email'] },
                { readonly columns: readonly ['userName'] },
              ];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly variants: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly name: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 255 };
                };
                readonly idProduct: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly color: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 255 };
                };
                readonly stock: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly variantCode: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'variants_idProduct_idx_101452b5';
                  readonly prefix: 'variants_idProduct_idx';
                  readonly columns: readonly ['idProduct'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'variants';
                    readonly columns: readonly ['idProduct'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'product';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
          };
          readonly valueSet: {
            readonly Methods: {
              readonly kind: 'valueSet';
              readonly values: readonly ['pix', 'cartão', 'boleto', 'paypal'];
            };
            readonly Status: {
              readonly kind: 'valueSet';
              readonly values: readonly ['concluído', 'em processo', 'recusado'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly categories: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Categories';
    };
    readonly orderItens: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'OrderItens';
    };
    readonly orders: { readonly namespace: 'public' & NamespaceId; readonly model: 'Orders' };
    readonly payment: { readonly namespace: 'public' & NamespaceId; readonly model: 'Payment' };
    readonly product: { readonly namespace: 'public' & NamespaceId; readonly model: 'Product' };
    readonly user: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
    readonly variants: { readonly namespace: 'public' & NamespaceId; readonly model: 'Variants' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Categories: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly categoryName: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 255 };
                };
              };
              readonly description: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 255 };
                };
              };
            };
            readonly relations: {
              readonly Product: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Product';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['idCategory'];
                };
              };
            };
            readonly storage: {
              readonly table: 'categories';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly categoryName: { readonly column: 'categoryName' };
                readonly description: { readonly column: 'description' };
              };
            };
          };
          readonly OrderItens: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly idOrder: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly idVariant: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly quantity: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly unitPrice: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly Orders: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Orders';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['idOrder'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly Variants: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Variants';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['idVariant'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'orderItens';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly idOrder: { readonly column: 'idOrder' };
                readonly idVariant: { readonly column: 'idVariant' };
                readonly quantity: { readonly column: 'quantity' };
                readonly unitPrice: { readonly column: 'unitPrice' };
              };
            };
          };
          readonly Orders: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly idUser: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly orderDate: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly orderStatus: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly OrderItens: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'OrderItens';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['idOrder'];
                };
              };
              readonly Payment: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Payment';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['idOrder'];
                };
              };
              readonly User: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['idUser'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'orders';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly idUser: { readonly column: 'idUser' };
                readonly orderDate: { readonly column: 'orderDate' };
                readonly orderStatus: { readonly column: 'orderStatus' };
              };
            };
          };
          readonly Payment: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly idUser: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly idOrder: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly paymentDate: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly paymentMetod: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly paymentStatus: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id_transacao_gateway: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly Orders: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Orders';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['idOrder'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly User: {
                readonly to: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['idUser'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'payment';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly idUser: { readonly column: 'idUser' };
                readonly idOrder: { readonly column: 'idOrder' };
                readonly paymentDate: { readonly column: 'paymentDate' };
                readonly paymentMetod: { readonly column: 'paymentMetod' };
                readonly paymentStatus: { readonly column: 'paymentStatus' };
                readonly id_transacao_gateway: { readonly column: 'id_transacao_gateway' };
              };
            };
          };
          readonly Product: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 255 };
                };
              };
              readonly idCategory: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly price: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly stock: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly description: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 255 };
                };
              };
            };
            readonly relations: {
              readonly Categories: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Categories';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['idCategory'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly Variants: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Variants';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['idProduct'];
                };
              };
            };
            readonly storage: {
              readonly table: 'product';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly idCategory: { readonly column: 'idCategory' };
                readonly price: { readonly column: 'price' };
                readonly stock: { readonly column: 'stock' };
                readonly description: { readonly column: 'description' };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 150 };
                };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 100 };
                };
              };
              readonly adress: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 255 };
                };
              };
              readonly password: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly userName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly Orders: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Orders';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['idUser'];
                };
              };
              readonly Payment: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Payment';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['idUser'];
                };
              };
            };
            readonly storage: {
              readonly table: 'user';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly email: { readonly column: 'email' };
                readonly name: { readonly column: 'name' };
                readonly adress: { readonly column: 'adress' };
                readonly password: { readonly column: 'password' };
                readonly userName: { readonly column: 'userName' };
              };
            };
          };
          readonly Variants: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 255 };
                };
              };
              readonly idProduct: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly color: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 255 };
                };
              };
              readonly stock: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly variantCode: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly OrderItens: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'OrderItens';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['idVariant'];
                };
              };
              readonly Product: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Product';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['idProduct'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'variants';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly idProduct: { readonly column: 'idProduct' };
                readonly color: { readonly column: 'color' };
                readonly stock: { readonly column: 'stock' };
                readonly variantCode: { readonly column: 'variantCode' };
              };
            };
          };
        };
        readonly enum: {
          readonly Methods: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'PIX'; readonly value: 'pix' },
              { readonly name: 'CARTAO'; readonly value: 'cartão' },
              { readonly name: 'BOLETO'; readonly value: 'boleto' },
              { readonly name: 'PAYPAL'; readonly value: 'paypal' },
            ];
          };
          readonly Status: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'COMPLETED'; readonly value: 'concluído' },
              { readonly name: 'PENDING'; readonly value: 'em processo' },
              { readonly name: 'REFUSED'; readonly value: 'recusado' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
